# -*- coding: utf-8 -*-
"""Final Project Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9s9LglNWLFrSyRWC7myE09Byf_VsEuB

#Import Library
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""#Import Data"""

df = pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv')
df

"""#Data Understanding"""

df.shape

df.info()

df.describe()

df['name'].unique()

df['fuel'].unique()

df['seller_type'].unique()

df['transmission'].unique()

df['owner'].unique()

"""#Data Cleaning"""

#copy data
df_clean = df.copy()

#Duplicate
df_clean.duplicated().sum()

df_clean = df_clean.drop_duplicates()

#missing values
df_clean.isnull().sum()

"""#Data Manipulation"""

#ekstrak kolom name menjadi brand
df_clean['brand'] = df_clean['name'].str.split().str[0]
df_clean = df_clean.drop(columns=['name'])

df_clean

df_clean['brand'].unique()

#ekstrak kolom year menjadi car_age
import datetime
current_year = datetime.datetime.now().year
df_clean['car_age'] = current_year - df_clean['year']
df_clean = df_clean.drop(columns=['year'])
df_clean

"""#EDA"""

df_clean['brand'].value_counts()

#Top 10 Brand
brand_counts = df_clean['brand'].value_counts().head(10)
plt.figure(figsize=(10,5))
sns.barplot(x=brand_counts.index, y=brand_counts.values)
plt.title('Top 10 Most Common Car Brands')
plt.xlabel('Brand')
plt.ylabel('Number of Cars')
plt.xticks(rotation=45)
plt.show()

#Car Age
df_clean['car_age'].value_counts()

plt.figure(figsize=(10,5))
sns.countplot(x='car_age', data=df_clean, order=sorted(df_clean['car_age'].unique()))
plt.title('Distribution of Car Age')
plt.xlabel('Car Age (Years)')
plt.ylabel('Number of Cars')
plt.show()

#Distribusi Harga
plt.figure(figsize=(8,5))
sns.histplot(df_clean['selling_price'], bins=40, kde=True)
plt.title('Distribution of Selling Prices')
plt.xlabel('Selling Price (INR)')
plt.ylabel('Count')
plt.show()

#Distribusi km_driven
plt.figure(figsize=(10,5))
sns.histplot(df_clean['km_driven'], kde=True, bins=30, color='skyblue')
plt.title('Distribution of Kilometers Driven')
plt.xlabel('Kilometers Driven')
plt.ylabel('Count')
plt.show()

#Distribusi Fuel Type
plt.figure(figsize=(8,5))
sns.countplot(data=df_clean, x='fuel', palette='Set2')
plt.title('Distribution of Fuel Types')
plt.xlabel('Fuel Type')
plt.ylabel('Number of Cars')
plt.show()

#Distribusi Owner
plt.figure(figsize=(8,5))
sns.countplot(data=df_clean, x='owner', palette='Pastel2')
plt.title('Distribution of Previous Owners')
plt.xlabel('Number of Previous Owners')
plt.ylabel('Number of Cars')
plt.xticks(rotation=45)
plt.show()

#Transmission
plt.figure(figsize=(7,5))
sns.countplot(data=df_clean, x='transmission', palette='cool')
plt.title('Distribution of Transmission Types')
plt.xlabel('Transmission Type')
plt.ylabel('Number of Cars')
plt.show()

#Price per brand
plt.figure(figsize=(12,6))
sns.boxplot(data=df_clean, x='brand', y='selling_price')
plt.title('Selling Price Distribution per Brand')
plt.xlabel('Brand')
plt.ylabel('Selling Price (INR)')
plt.xticks(rotation=75)
plt.yscale('log')
plt.show()

plt.savefig("boxplot_brand_tier.png", dpi=300, bbox_inches='tight')  # simpan di folder kerja colab
plt.show()

from google.colab import files
files.download("boxplot_brand_tier.png")

"""#Mapping Brand Tier"""

high_tier = ['Mercedes-Benz', 'BMW', 'Audi', 'Jaguar', 'Volvo']
mid_tier = ['Toyota', 'Honda', 'Hyundai', 'Skoda', 'Mahindra', 'Jeep']
low_tier = ['Maruti', 'Tata', 'Renault', 'Datsun', 'Ford', 'Nissan', 'Chevrolet']
other_tier = ['Land', 'MG', 'Daewoo', 'Force', 'Isuzu', 'OpelCorsa', 'Ambassador', 'Kia']

def brand_tier(brand):
    if brand in high_tier:
        return 'High'
    elif brand in mid_tier:
        return 'Mid'
    elif brand in low_tier:
        return 'Low'
    else:
        return 'Other'

df_clean['brand_tier'] = df_clean['brand'].apply(brand_tier)

df_clean['brand_tier'].value_counts()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
sns.countplot(x='brand_tier', data=df_clean, order=['High', 'Mid', 'Low', 'Other'])
plt.title('Distribution of Brand Tiers')
plt.xlabel('Brand Tier')
plt.ylabel('Number of Cars')
plt.show()

df_clean.drop('brand', axis=1, inplace=True)

df_clean.head()

"""#Separate target and feature"""

X = df_clean.drop(columns='selling_price')
y = df_clean['selling_price']

"""#Feature Engineering"""

#Label encoder for brand_tier
brand_tier_map = {'Low': 0, 'Mid': 1, 'High': 2, 'Other': 3}
X['brand_tier'] = X['brand_tier'].map(brand_tier_map)

#One Hot encoder for other feature
categorical_cols = ['fuel', 'seller_type', 'transmission', 'owner']
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True).astype(int)

X

"""#Split train-test"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

"""#Multicollinearity test

"""

from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

vif_data = vif_data.sort_values(by="VIF", ascending=False).reset_index(drop=True)
print(vif_data)

#drop
X_reduced = X.drop(columns=['fuel_Petrol'])

corr = X_reduced[['car_age', 'km_driven']].corr()
print(corr)

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Gabungkan kembali X_test dan y_test
test_data = X_test.copy()
test_data["selling_price"] = y_test

# Ambil kolom numerik saja
numeric_test = test_data.select_dtypes(include=['number'])

# Hitung korelasi
corr_test = numeric_test.corr()

# Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(corr_test, annot=True, fmt=".2f", cmap="coolwarm", cbar=True)
plt.title("Correlation Heatmap (Test Set)", fontsize=14)
plt.show()

# Korelasi tiap fitur terhadap target
target_corr_test = corr_test["selling_price"].sort_values(ascending=False)
print(target_corr_test)

from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

vif_data = pd.DataFrame()
vif_data["Feature"] = X_reduced.columns
vif_data["VIF"] = [variance_inflation_factor(X_reduced.values, i) for i in range(X_reduced.shape[1])]

print(vif_data.sort_values(by="VIF", ascending=False))

"""#Modelling

##Linear Reggression
"""

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
}).sort_values(by="Coefficient", ascending=False)

coefficients

"""##Ridge Regression"""

from sklearn.linear_model import Ridge
import pandas as pd

ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train, y_train)

ridge_coefficients = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": ridge_model.coef_
}).sort_values(by="Coefficient", ascending=False)

ridge_coefficients

"""##Lasso Regression"""

from sklearn.linear_model import Lasso
import pandas as pd

lasso_model = Lasso(alpha=1.0)
lasso_model.fit(X_train, y_train)

lasso_coefficients = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": lasso_model.coef_
}).sort_values(by="Coefficient", ascending=False)

lasso_coefficients

"""#Model Evaluation"""

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd

# List model yang ingin dibandingkan
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=0.1)
}

# List untuk menyimpan hasil
results_list = []

for name, model in models.items():
    # Fit model
    model.fit(X_train, y_train)

    # Training error
    y_train_pred = model.predict(X_train)
    results_list.append({
        "Model": name,
        "Dataset": "Train",
        "MAE": mean_absolute_error(y_train, y_train_pred),
        "MSE": mean_squared_error(y_train, y_train_pred),
        "RMSE": np.sqrt(mean_squared_error(y_train, y_train_pred)),
        "R2": r2_score(y_train, y_train_pred)
    })

    # Test error
    y_test_pred = model.predict(X_test)
    results_list.append({
        "Model": name,
        "Dataset": "Test",
        "MAE": mean_absolute_error(y_test, y_test_pred),
        "MSE": mean_squared_error(y_test, y_test_pred),
        "RMSE": np.sqrt(mean_squared_error(y_test, y_test_pred)),
        "R2": r2_score(y_test, y_test_pred)
    })

# Convert list ke DataFrame
results = pd.DataFrame(results_list)

# Tampilkan hasil
results
